global:
    scrape_interval: 30s
    evaluation_interval: 30s

rule_files:
   - alert.rules.yml
#   - "/etc/prometheus/alert.rules.yml"
   - /etc/prometheus/rules.yml
#   - "/etc/prometheus/alert.rules.yml"
   
#  - alert.yml
#  - "alert.yml"
#  - "/etc/prometheus/rules.yml"
#  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
#    scrape_interval: 30s
    
    static_configs:
      - targets: ['localhost:9090']
      - labels:
          host: 'HOST'
          
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          hosts: 'MYPC'
#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'
#global:
#  scrape_interval: 10s
#scrape_configs:
# - job_name: prometheus
#   static_configs:
#    - targets:
#       - prometheus:9090
